/*  =========================================================================
    fty-common-messagebus - generated layer of public API

    Copyright (C) 2014 - 2020 Eaton

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License along
    with this program; if not, write to the Free Software Foundation, Inc.,
    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
    =========================================================================
*/

#ifndef FTY_COMMON_MESSAGEBUS_LIBRARY_H_INCLUDED
#define FTY_COMMON_MESSAGEBUS_LIBRARY_H_INCLUDED

//  Set up environment for the application

//  External dependencies
#include <czmq.h>
#include <malamute.h>
#include <fty_log.h>

//  Opaque class structures to allow forward references
//  These classes are stable or legacy and built in all releases
//  Draft classes are by default not built in stable releases
typedef struct _fty_common_messagebus_dto_t fty_common_messagebus_dto_t;
#define FTY_COMMON_MESSAGEBUS_DTO_T_DEFINED
typedef struct _fty_common_messagebus_interface_t fty_common_messagebus_interface_t;
#define FTY_COMMON_MESSAGEBUS_INTERFACE_T_DEFINED
typedef struct _fty_common_messagebus_dispatcher_t fty_common_messagebus_dispatcher_t;
#define FTY_COMMON_MESSAGEBUS_DISPATCHER_T_DEFINED
typedef struct _fty_common_messagebus_pool_worker_t fty_common_messagebus_pool_worker_t;
#define FTY_COMMON_MESSAGEBUS_POOL_WORKER_T_DEFINED


//  Public classes, each with its own header file
#include "fty_common_messagebus_exception.h"
#include "fty_common_messagebus_message.h"
#include "fty_common_messagebus_dto.h"
#include "fty_common_messagebus_interface.h"
#include "fty_common_messagebus_dispatcher.h"
#include "fty_common_messagebus_pool_worker.h"


#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#endif
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
*/
